/*
 * si5432_axi_iic.h
 *
 *  Created on: Aug 7, 2020
 *      Author: bvanca
 */

#ifndef SRC_SI5432_AXI_IIC_H_
#define SRC_SI5432_AXI_IIC_H_

#include "xparameters.h"
#include "xiic.h"
#include "xil_printf.h"
#include "xstatus.h"
#include "xil_types.h"

#define SEND_BUFFER_SIZE    2

#define I2C_SI5342_ADDR    0x68  /**< I2C Clk Address Si5342*/
// SI5432 defines
#define SI_5432_PAGE        0x01
#define IO_VDD_SEL_ADDR     0x0943


#define SI5342_REVD_REG_CONFIG_NUM_REGS			411
#define HOLDOVER_AND_LOL_STATUS     0x000E
#define HDMI_TMDS_ID_BASE_ADDR    0x00
#define HDMI_SI5432_ID_BASE_ADDR  0x02
#define PLL_MAX_LOCK_TIME         300

/******************************************************************************
 * Defines independent on the specific board design. Should not be changed.
 *****************************************************************************/

/**
 * Debug output enable. Set to TRUE to enable debug prints,
 * to FALSE to disable debug prints.
 */
#define SI5342_DEBUG FALSE

/**
 * The following constants are error codes generated by the functions in
 * this driver.
 */
#define SI5342_SUCCESS      0 /**< Operation was successful */
#define SI5342_ERR_IIC     -1 /**< IIC error occurred */
#define SI5342_ERR_PARM    -3 /**< Invalid parameter */


typedef struct
{
	unsigned int address; /* 16-bit register address */
	unsigned char value; /* 8-bit register data */

} si5342_revd_register_t;

extern si5342_revd_register_t const si5342_revd_registers_jitteratt[SI5342_REVD_REG_CONFIG_NUM_REGS];


/*****************************************************************************/
/**
 * Reset the SiliconLabs Si5342 clock generator.
 *
 * @param    IICBaseAddress contains the base address of the IIC master
 *           device.
 * @param    IICAddress contains the 7 bit IIC address of the Si5342 device.
 *
 * @return   SI5342_SUCCESS for success, SI5342_ERR_IIC for IIC access failure.
 *
 * @note     Private function.
 *****************************************************************************/
XStatus Si5342_SetI2cDriveLevel();

void hdmi_config_interface_get_SI5432_write_config_registers(uint8_t device_addr, si5342_revd_register_t const Config[], const uint16_t ConfigLength);

void hdmi_config_interface_get_SI5432_verify_config_registers(uint8_t device_addr, si5342_revd_register_t const Config[], const uint16_t ConfigLength);
int check_hdmi_lol_status();



#endif /* SRC_SI5432_AXI_IIC_H_ */
